AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for Cluster Autoscaler on EKS

Parameters:
  OIDCProviderUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /eks/doggy-app/oidc

Resources:
  ClusterAutoscalerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cluster-autoscaler-role-doggyapp-ka
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDCProviderUrl}
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                Fn::Sub:
                  - "${OIDCProviderUrl}:sub"
                  - OIDCProviderUrl: !Ref OIDCProviderUrl
                    sub: "system:serviceaccount:kube-system:cluster-autoscaler"
      Policies:
        - PolicyName: ClusterAutoscalerPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeTags
                  - autoscaling:SetDesiredCapacity
                  - autoscaling:TerminateInstanceInAutoScalingGroup
                  - ec2:DescribeLaunchTemplateVersions
                Resource: "*"
