apiVersion: v1
kind: Service
metadata: 
  name: doggy-webapp
spec: 
  selector: 
    app: webapp
  ports: 
    - name: http
      port: 3000
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata: 
  name: registry-service
spec: 
  selector: 
    microsvc: registry
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP