
deploymentMode: SingleBinary

singleBinary:
  replicas: 1

  nodeSelector:
    workload: monitoring

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

  persistence:
    enabled: false

  extraVolumes:
    - name: loki-chunks
      emptyDir: {}
    - name: loki-rules
      configMap:
        name: loki-alert-rules
    - name: loki-compactor
      emptyDir: {}
    - name: loki-tsdb-cache
      emptyDir: {}
    - name: loki-tsdb-active
      emptyDir: {}
    - name: loki-wal
      emptyDir: {}

  extraVolumeMounts:
    - name: loki-chunks
      mountPath: /tmp/loki/chunks
    - name: loki-rules
      mountPath: /tmp/loki/rules/fake
      readOnly: true
    - name: loki-compactor
      mountPath: /tmp/loki/compactor
    - name: loki-tsdb-cache
      mountPath: /tmp/loki/tsdb-shipper-cache
    - name: loki-tsdb-active
      mountPath: /tmp/loki/tsdb-shipper-active
    - name: loki-wal
      mountPath: /tmp/loki/wal


# Shut down all microservices so that the monolithic architecture can be used instead 
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
distributor:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  commonConfig:
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
    replication_factor: 1
    path_prefix: /tmp/loki

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storage:
    type: filesystem

  # rulerConfig:
  #   enabled: false

  storage_config:
    filesystem:
      directory: /tmp/loki/chunks

  compactor:
    working_directory: /tmp/loki/compactor

  rulerConfig:
    enable_api: true
    storage:
      type: local
      local:
        directory: /tmp/loki/rules
    rule_path: "/tmp/loki/rules"
    ring:
        kvstore:
          store: inmemory
    enable_alertmanager_v2: true
    alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring:9093

monitoring:
  alerts:
    enabled: true
    labels:
      release: kube-prometheus-stack
  dashboards:
    enabled: true
    labels:
      release: kube-prometheus-stack
  rules:
    enabled: true
    labels:
      release: kube-prometheus-stack
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: true
    interval: 1m
    labels:
      release: kube-prometheus-stack
    scrapeTimeout: 10s