prometheus:
  prometheusSpec:
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    nodeSelector:
      workload: monitoring
    maximumStartupDurationSeconds: 300

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

grafana:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
      editable: true

kubeStateMetrics:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

nodeExporter:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"