apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alert-rules
  labels:
    release: monitoring-metrics
data:
  rules.yaml: |
    groups:
      - name: angular-frontend-errors
        rules:
          - alert: AngularFrontendError
            expr: |
              count_over_time({app="webapp"} |= "(?i)error" [5m]) > 0 
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Unhandled error in Angular frontend"
              description: "Detected 'Error:' log entries from container 'webapp' in the last 5 minutes."
    
      - name: springboot-backend-errors
        rules:
          - alert: SpringBootExceptionDetected
            expr: |
              count_over_time({app="registry"} |= "(?i)error" [5m]) > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Spring Boot backend exception detected"
              description: "Detected exception log entries from container 'registry' in the last 5 minutes"

