apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doggy-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "60"  # 60 requests per minute
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-exempt: "127.0.0.1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(?!api)(.*)$ /index.html break;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /api/registry/
          pathType: Prefix
          backend:
            service:
              name: registry-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: doggy-webapp
              port:
                number: 80
