apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doggy-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "60"  # 60 requests per minute
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-exempt: "127.0.0.1"
    # nginx.ingress.kubernetes.io/rewrite-target: /index.html
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(?!registry|assets|favicon\.ico|.*\.(js|css|png|jpg|woff2?|ttf|svg))$ /index.html break;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /(.+\.(js|css|png|jpg|jpeg|svg|woff2?|ttf|ico))
          pathType: ImplementationSpecific
          backend:
            service:
              name: doggy-webapp
              port:
                number: 80
        - path:  /registry(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: registry-service
              port:
                number: 8080
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: doggy-webapp
              port:
                number: 80

