global:
  resolve_timeout: 5m

route:
  receiver: openai-webhook
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m

receivers:
  - name: openai-webhook
    webhook_configs:
      - url: http://${BASTION_IP}:5000/webhook
        send_resolved: true
