alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'webhook'
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: 'webhook'
    receivers:
      - name: 'webhook'
        webhook_configs:
          - url: 'http://alert-analyzer-service.monitoring.svc.cluster.local/webhook'
    inhibit_rules:
      - source_matchers: ['severity = critical']
        target_matchers: ['severity = warning|info']
        equal: ['namespace', 'alertname']