AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for Cluster Autoscaler and secrets manager access on EKS

Resources:
  ClusterAlerterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: doggy-alert-analyzer-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::$AWS_ID:oidc-provider/$OIDC_URL
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals: 
                "$OIDC_URL:sub" : "system:serviceaccount:monitoring:alert-analyzer"
      Policies:
        - PolicyName: WebhookSecretCaller
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "$OPENIA_KEY"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "$SNS_TOPIC_ARN"


Outputs:
  ClusterAlerterRoleArn:
    Description: ARN of the Cluster Alerter IAM Role
    Value: !Ref ClusterAlerterRole
    Export:
      Name: ClusterAlerterRoleArn