AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for Cluster Autoscaler and secrets manager access on EKS

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: doggy-alerts
      DisplayName: "Doggy Alerts"

  SNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: $EMAIL 
      TopicArn: !Ref SNSTopic

  OpenAISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: openAI-key-doggy
      Description: open AI api key 
      SecretString: '{"openai-api-key-doggy":"$OPENIA_KEY"}'

Outputs:
  SNSTopicArn:
    Description: ARN of the created SNS Topic
    Value: !Ref SNSTopic

  OpenAISecretArn:
    Description: ARN of the cOpenAI Secret key 
    Value: !Ref OpenAISecret