---
- name: Deploy full Kubernetes stack to AWS using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
    - name: email
      prompt: "We need your email to set up the SNS service, it won't go anywhere"
      private: False
      default: "idanzigm@gmail.com"
    - name: aws_id
      prompt: "We also need your AWS ID to set up everything, it won't go anywhere"
      private: False
      default: "109798190983"
    - name: openai_key
      prompt: "Enter your OpenAI API key (you need to purchase credits on OpenAI for the integration to work, 2$ is more than enough for a demo)"
      private: True
  vars:
    cluster_name: "doggy-app-eks-cluster-0"
    nodegroup_name: "doggy-app-eks-ng-monitoring"
    region: "us-east-1"
    config_dir: "/home/ec2-user/config"
    arch_dir: "/home/ec2-user/kubernetesArchitecture/kubernetes"

  tasks:

    - name: Ensure /home/ec2-user/config directory exists
      file:
        path: /home/ec2-user/config
        state: directory
        mode: '0755'
        
    - name: Update kubeconfig
      shell: aws eks update-kubeconfig --region {{ region }} --name {{ cluster_name }} --profile eks-cluster-admin

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Associate IAM OIDC provider
      shell: eksctl utils associate-iam-oidc-provider --cluster {{ cluster_name }} --approve

    - name: Get OIDC URL
      shell: |
        aws eks describe-cluster \
          --name {{ cluster_name }} \
          --query "cluster.identity.oidc.issuer" \
          --output text | sed 's|https://||'
      register: oidc_url

    - name: Template the autoscaler role YAML
      shell: |
        envsubst {{ arch_dir }}/autoscaler/cf-autoscaler-role.yaml > {{ config_dir }}/cf-autoscaler-role-up.yaml
      environment:
        OIDC_URL: "{{ oidc_url }}"
        AWS_ID: "{{ aws_id }}"
        
    - name: Deploy autoscaler role stack
      shell: |
        aws cloudformation deploy \
          --template-file {{ config_dir }}/cf-autoscaler-role-up.yaml \
          --stack-name cluster-autoscaler-iam-role \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Get autoscaler role ARN
      shell: |
        aws cloudformation describe-stacks \
          --stack-name cluster-autoscaler-iam-role \
          --query "Stacks[0].Outputs[?OutputKey=='ClusterAutoscalerRoleArn'].OutputValue" \
          --output text
      register: autoscaler_role_arn

    - name: Template the autoscaler values
      template:
        src: "{{ arch_dir }}/autoscaler/autoscaler-values.yaml.j2"
        dest: "{{ config_dir }}/autoscaler-values-up.yaml"

    - name: Add autoscaler Helm repo
      kubernetes.core.helm:
        name: autoscaler
        repo_url: https://kubernetes.github.io/autoscaler

    - name: Update Helm repos
      shell: helm repo update

    - name: Deploy Cluster Autoscaler
      kubernetes.core.helm:
        name: cluster-autoscaler
        chart_ref: autoscaler/cluster-autoscaler
        release_namespace: kube-system
        create_namespace: true
        values_files:
          - "{{ config_dir }}/autoscaler-values-up.yaml"

    - name: Pause for autoscaler setup
      pause:
        seconds: 15

    - name: Create ingress namespace
      shell: kubectl create namespace ingress-nginx

    - name: Apply ingress
      shell: kubectl apply -k {{ arch_dir }}/ingress/

    - name: Pause for ingress setup
      pause:
        seconds: 30

    - name: Get LoadBalancer hostname
      shell: |
        kubectl get ingress doggy-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: lb_host

    - name: Create frontend config map
      shell: |
        kubectl create configmap frontend-config \
          --from-literal=LOAD_BALANCER_URL=http://{{ lb_host.stdout }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply application pods and services
      shell: |
        kubectl apply -f {{ arch_dir }}/default/pods.yaml
        kubectl apply -f {{ arch_dir }}/default/services.yaml

    - name: Create monitoring namespace
      shell: kubectl create namespace monitoring

    - name: Add Prometheus Helm repo
      kubernetes.core.helm:
        name: prometheus-stack
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Install Prometheus stack
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values_files:
          - "{{ arch_dir }}/monitoring/prometheus/prometheus-values.yaml"

    - name: Add Grafana Helm repo
      kubernetes.core.helm:
        name: Grafan
        repo_url: https://grafana.github.io/helm-charts

    - name: Apply Loki alert rules
      shell: kubectl apply -f {{ arch_dir }}/monitoring/loki/loki-alert-rules.yaml -n monitoring

    - name: Install Loki
      kubernetes.core.helm:
        name: loki
        chart_ref: grafana/loki
        release_namespace: monitoring
        create_namespace: true
        values_files:
          - "{{ arch_dir }}/monitoring/loki/loki-values.yaml"

    - name: Install Promtail
      kubernetes.core.helm:
        name: promtail
        chart_ref: grafana/promtail
        release_namespace: monitoring
        create_namespace: true
        values_files:
          - "{{ arch_dir }}/monitoring/promtail/promtail-values.yaml"

    - name: Render the SNS stack
      shell: |
        envsubst {{ arch_dir }}/monitoring/alerting/cf-sns.yaml > {{ config_dir }}/cf-sns-up.yaml
      environment: 
        OPENIA_KEY: "{{ openai_secret_arn }}"
        EMAIL: "{{ email }}"

    - name: Deploy SNS and secret stack
      shell: aws cloudformation deploy --template-file {{ config_dir }}/cf-sns-up.yaml --stack-name sns-and-secret-doggy

    - name: Return secret ARN
      shell: |
        aws cloudformation describe-stacks --stack-name sns-and-secret-doggy --query "Stacks[0].Outputs[?OutputKey=='OpenAISecretArn'].OutputValue" --output text
      register: openai_secret_arn

    - name: Return SNS ARN 
      shell: |
        aws cloudformation describe-stacks --stack-name sns-and-secret-doggy --query "Stacks[0].Outputs[?OutputKey=='SNSTopicArn'].OutputValue" --output text
      register: sns_topic_arn 

    - name: Render alert hook role
      shell: |
        envsubst {{ arch_dir }}/monitoring/alerting/cf-alert-hook-role.yaml > {{ config_dir }}/cf-alert-hook-role-up.yaml
      environment: 
        AWS_ID: "{{ aws_id }}"
        OIDC_URL: "{{ oidc_url }}"
        OPENIA_KEY: "{{ openai_secret_arn }}"
        SNS_TOPIC_ARN: "{{ sns_topic_arn }}"

    - name: Deploy alert hook IAM role
      shell: aws cloudformation deploy --template-file {{ config_dir }}/cf-alert-hook-role-up.yaml --stack-name alert-hook-iam-role --capabilities CAPABILITY_NAMED_IAM

    - name: Get alert hook role ARN
      shell: |
        aws cloudformation describe-stacks \
          --stack-name alert-hook-iam-role \
          --query "Stacks[0].Outputs[?OutputKey=='ClusterAlerterRoleArn'].OutputValue" \
          --output text
      register: alerter_role_arn

    - name: Render alert service account
      template:
        src: "{{ arch_dir }}/monitoring/alerting/alert-service-account.yaml.j2"
        dest: "{{ config_dir }}/alert-service-account-up.yaml"

    - name: Apply alert service account
      shell: |
        kubectl apply -f {{ config_dir }}/alert-service-account-up.yaml

    - name: Render alert pod
      template:
        src: "{{ arch_dir }}/monitoring/alerting/alert-pod.yaml.j2"
        dest: "{{ config_dir }}/alert-pod-up.yaml"

    - name: Apply alert pod
      shell: |
        kubectl apply -f {{ config_dir }}/alert-pod-up.yaml
...
