---
- name: Tear down the full Kubernetes stack on AWS using Ansible
  hosts: localhost
  connection: local
  gather_facts: False


  vars:
    cluster_name: "doggy-app-eks-cluster-0"
    nodegroup_name: "doggy-app-eks-ng-monitoring"
    region: "us-east-1"
    config_dir: "/home/ec2-user/config"
    arch_dir: "/home/ec2-user/kubernetesArchitecture/kubernetes"

    
  tasks:

    - name: Delete doggy ingress
      kubernetes.core.k8s:
        state: absent
        kind: Ingress
        namespace: default
        name: doggy-ingress
      ignore_errors: true

    - name: Uninstall ingress-nginx Helm release
      kubernetes.core.helm:
        name: ingress-nginx
        release_namespace: ingress-nginx
        state: absent
      ignore_errors: true  

    - name: Delete ingress-nginx namespace
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: ingress-nginx
      ignore_errors: true  

    - name: Uninstall Promtail stack
      kubernetes.core.helm:
        name: promtail
        release_namespace: monitoring
        state: absent

    - name: Uninstall Loki stack
      kubernetes.core.helm:
        name: loki
        release_namespace: monitoring
        state: absent

    - name: Uninstall Prometheus stack
      kubernetes.core.helm:
        name: kube-prometheus-stack
        release_namespace: monitoring
        state: absent

    - name: Uninstall cluster autoscaler
      kubernetes.core.helm:
        name: cluster-autoscaler
        release_namespace: kube-system
        state: absent

    - name: Return SNS ARN 
      shell: |
        aws cloudformation describe-stacks --stack-name sns-doggy --query "Stacks[0].Outputs[?OutputKey=='SNSTopicArn'].OutputValue" --output text
      register: sns_topic_arn

    - name: Unsubscribe all SNS subscriptions for the topic
      shell: |
        for arn in $(aws sns list-subscriptions-by-topic \
                       --topic-arn "{{ sns_topic_arn.stdout }}" \
                       --query 'Subscriptions[?SubscriptionArn!=`PendingConfirmation`].SubscriptionArn' \
                       --output text); do
          aws sns unsubscribe --subscription-arn "$arn"
        done
      environment:
        AWS_REGION: us-east-1


    - name: Delete SNS CloudFormation stack
      amazon.aws.cloudformation:
        stack_name: sns-doggy
        state: absent

    - name: Delete autoscaler role CloudFormation stack
      amazon.aws.cloudformation:
        stack_name: cluster-autoscaler-iam-role
        state: absent

    - name: Delete Loki alert rules
      shell: kubectl delete -f "{{ arch_dir }}/monitoring/loki/loki-alert-rules.yaml" -n monitoring
      ignore_errors: true

    - name: Delete alert hook IAM role CloudFormation stack
      amazon.aws.cloudformation:
        stack_name: alert-hook-iam-role
        state: absent

    - name: Delete web app pods
      kubernetes.core.k8s:
        state: absent
        src: "{{ arch_dir }}/default/pods.yaml"

    - name: Delete web app services
      kubernetes.core.k8s:
        state: absent
        src: "{{ arch_dir }}/default/services.yaml"

    - name: Delete ingress-nginx namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ingress-nginx
        state: absent

    - name: Delete monitoring namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: monitoring
        state: absent

    - name: Delete config directory
      become: true
      file:
        path: "/home/ec2-user/config"
        state: absent

...