AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for Cluster Autoscaler and secrets manager access on EKS

Resources:
  ClusterAutoscalerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cluster-autoscaler-role-doggyapp-ka
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::$AWS_ID:oidc-provider/$OIDC_URL
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals: 
                "$OIDC_URL:sub" : "system:serviceaccount:kube-system:cluster-autoscaler"

      Policies:
        - PolicyName: ClusterAutoscalerPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeTags
                  - autoscaling:SetDesiredCapacity
                  - autoscaling:TerminateInstanceInAutoScalingGroup
                  - ec2:DescribeLaunchTemplateVersions
                Resource: "*"




Outputs:
  ClusterAutoscalerRoleArn:
    Description: ARN of the Cluster Autoscaler IAM Role
    Value: !GetAtt ClusterAutoscalerRole.Arn 
    Export:
      Name: ClusterAutoscalerRoleArn
