apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: loki-app-alerts
  namespace: monitoring  # use the namespace where your Prometheus stack is deployed
  labels:
    release: kube-prometheus-stack  # this label MUST match your Helm release name
spec:
  groups:
    - name: angular-frontend-errors
      rules:
        - alert: AngularFrontendError
          expr: |
            count_over_time({app="webapp"} |= "(?i)error" [5m]) > 0 
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Unhandled error in Angular frontend"
            description: "Detected 'error' log entries from app=webapp in the last 5 minutes."

    - name: springboot-backend-errors
      rules:
        - alert: SpringBootExceptionDetected
          expr: |
            count_over_time({app="registry"} |= "(?i)error" [5m]) > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Spring Boot backend exception detected"
            description: "Detected 'error' log entries from app=registry in the last 5 minutes."
