apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doggy-ingress
  namespace: default
  annotations:
    # Apply rewrite-target only to /api/* paths
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        # For /api/ paths, we want to strip the /api prefix
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: registry-service
              port:
                number: 8080
        # For all other requests (static assets, frontend), no rewrite needed
        - path: /styles.css
          pathType: Exact
          backend:
            service:
              name: doggy-webapp
              port:
                number: 3000
        - path: /main.js
          pathType: Exact
          backend:
            service:
              name: doggy-webapp
              port:
                number: 3000
        # Handle the rest of the paths for the frontend
        - path: /
          pathType: Prefix
          backend:
            service:
              name: doggy-webapp
              port:
                number: 3000

