resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
  - doggy-ingress.yaml 
  
patches:
  - path: svc-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller