AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for the AWS EFS CSI driver (IRSA)

Resources:
  EfsCsiDriverRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: efs-csi-driver-role-doggyapp
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: "arn:aws:iam::${AWS_ID}:oidc-provider/${OIDC_URL}"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "${OIDC_URL}:sub": "system:serviceaccount:kube-system:efs-csi-controller-sa"
                "${OIDC_URL}:aud": "sts.amazonaws.com"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy

Outputs:
  EfsCsiDriverRoleArn:
    Value: !GetAtt EfsCsiDriverRole.Arn
    Export:
      Name: EfsCsiDriverRoleArn
