AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for the AWS EBS CSI driver (IRSA)

Resources:
  EbsCsiDriverRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ebs-csi-driver-role-doggyapp
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: "arn:aws:iam::${AWS_ID}:oidc-provider/${OIDC_URL}"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "${OIDC_URL}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                "${OIDC_URL}:aud": "sts.amazonaws.com"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

Outputs:
  EbsCsiDriverRoleArn:
    Value: !GetAtt EbsCsiDriverRole.Arn
    Export:
      Name: EbsCsiDriverRoleArn
