apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: webapp 
spec: 
  selector: 
    matchLabels: 
      app: webapp
  replicas: 1
  template: 
    metadata:
      labels: 
        app: webapp 
    spec: 
      terminationGracePeriodSeconds: 30
      containers: 
        - name: webapp 
          image: idanzigm/frontend-doggy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: LOAD_BALANCER_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: LOAD_BALANCER_URL

--- 
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: registry
spec: 
  selector: 
    matchLabels: 
      app: registry
  replicas: 1 
  template: 
    metadata:
      labels: 
        app: registry
    spec: 
      containers: 
        - name: registry 
          image: idanzigm/registry-doggy:v100
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"