apiVersion: v1
kind: Service
metadata: 
  name: doggy-webapp
spec: 
  selector: 
    app: webapp
  ports: 
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata: 
  name: registry-service
spec: 
  selector: 
    app: registry
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
