apiVersion: loki.grafana.com/v1
kind: AlertingRule
metadata:
  name: frontend-backend-errors
  namespace: monitoring
spec:
  groups:
    - name: angular-error-alerts
      rules:
        - alert: AngularFrontendException
          expr: |
            sum by (namespace, pod, container) (
              count_over_time(
                {namespace="default", container="webapp"} |= "Error:" [1m]
              )
            ) > 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Unhandled Angular frontend exception"
            description: |
              Error log detected in pod {{ $labels.pod }} (namespace {{ $labels.namespace }}).

    - name: springboot-error-alerts
      rules:
        - alert: SpringBootBackendException
          expr: |
            sum by (namespace, pod, container) (
              count_over_time(
                {namespace="default", container="registry"} |= "Exception" [1m]
              )
            ) > 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Spring Boot backend exception"
            description: |
              Exception detected in pod {{ $labels.pod }} (namespace {{ $labels.namespace }}).
